### ISSUE TITLE
Unescaped argument lps2bpes

### ISSUE THREAD

**Issue by nbelzer** [casperbp/mcrl2-mode#1]
https://github.com/casperbp/mcrl2-mode/blob/96400366081769094ad0fe6b75c7f5b8545fbb5d/mcrl2-mode.el#L157

I had some trouble with the `mcf-create-lps-pbes` function as my folder path to the `.lps` file contains spaces for one of the folders in the path. This caused the command to fail as it detects too many arguments (separated by the spaces). This seems to be the only path that is not properly escaped by the `shell-quote-argument` function. Adding the `shell-quote-argument` function over the `read-file-name` (as shown below) solves the issue.

```emacs-lisp
; I changed this line (157):
                     (read-file-name "Enter .lps file name:") 
; To the following:
                     (shell-quote-argument (read-file-name "Enter .lps file name:"))
```

As I'm not sure on your preference for contribution, I'll leave this here as an issue.

**Comment by casper-bach** [comment]
This should be done indeed.

If you make a PR I'll merge!
